watch: fixup build with glibc-2.42
Build fails with
```
src/watch.c:105:28: error: 'true' undeclared here (not in a function)
  105 | static bool first_screen = true, screen_size_changed, screen_changed;
      |                            ^~~~
src/watch.c:62:1: note: 'true' is defined in header '<stdbool.h>'; this is probably fixable by adding '#include <stdbool.h>'
   61 | #include "xalloc.h"
  +++ |+#include <stdbool.h>
   62 |
```
add the missing include.